name: basebuild

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.4'

      - name: Build frontend
        run: cd frontend && yarn && yarn build

      - name: Run GoReleaser
        run: CGO_ENABLED=0 go build -o teester
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: teester-linux-64
          path: ./teester
