name: basebuild

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20.4"

      - name: Build frontend
        run: cd frontend && yarn && yarn build

      - name: build Go binary linux
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o teester-linux-64

      - name: build Go binary windows
        run: GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o teester-windows-64.exe

      - name: Upload a Build Artifact for linux
        uses: actions/upload-artifact@v3.1.2
        with:
          name: teester-linux-64
          path: ./teester-linux-64
      
      - name: Upload a Build Artifact for windows
        uses: actions/upload-artifact@v3.1.2
        with:
          name: teester-windows-64.exe
          path: ./teester-windows-64.exe
